# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"save_file_from_url": "00.ipynb",
         "SaveFeatures": "00.ipynb",
         "nas_pictures_path": "00_paths.ipynb",
         "ssd_pictures_path": "00_paths.ipynb",
         "models_path": "00_paths.ipynb"}

modules = ["learn.py",
           "paths.py"]

doc_url = "https://fastai.github.io/fur/"

git_url = "https://github.com/fastai/fur/tree/master/"

def custom_doc_links(name): return None
