# AUTOGENERATED! DO NOT EDIT! File to edit: 00.ipynb (unless otherwise specified).

__all__ = ['save_file_from_url', 'SaveFeatures']

# Cell
import pandas as pd
from pymongo import MongoClient
from pathlib import Path
import shutil
from mytools.tools import *
from .paths import *
from annoy import AnnoyIndex

from fastai.vision.all import *

import nested_lookup

# Cell
def save_file_from_url(url, fname):
    r = requests.get(url, allow_redirects=True)
    open(fname, 'wb').write(r.content)

# Cell
# this is a hook (learned about it here: https://forums.fast.ai/t/how-to-find-similar-images-based-on-final-embedding-layer/16903/13)
# hooks are used for saving intermediate computations
class SaveFeatures():
    features=None
    def __init__(self, m):
        self.hook = m.register_forward_hook(self.hook_fn)
        self.features = None
    def hook_fn(self, module, input, output):
        out = output.detach().cpu().numpy()
        if isinstance(self.features, type(None)):
            self.features = out
        else:
            self.features = np.row_stack((self.features, out))
    def remove(self):
        self.hook.remove()
