# AUTOGENERATED! DO NOT EDIT! File to edit: 00_paths.ipynb (unless otherwise specified).

__all__ = ['nas_pictures_path', 'ssd_pictures_path', 'models_path']

# Cell
from mytools.tools import *
from pathlib import Path

# Cell
nas_pictures_path = Path('/home/dima/nas/real_nas/houzz/pictures')
ssd_pictures_path = Path('/home/dima/ssd/furniture_data/pictures')
models_path       = Path('/home/dima/furniture_data/models')